version: '3.7'

services:
    database_fiis:
      image: postgres
      container_name: database_fiis
      restart: always
      ports:
        - 5431:5432
      env_file: .env
      environment:
        - POSTGRES_USER=$POSTGRES_USER
        - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
        - POSTGRES_DB=$POSTGRES_DB
      volumes:
          - pgdata:/data/postgres
    app:
        build: .
        container_name: api-fii
        ports:
          - 3334:3334
        volumes:
            - .:/usr/app
        links:
            - database_fiis
        depends_on: 
            - database_fiis
        security_opt:
            - seccomp=chrome.json
volumes:
    pgdata:
        driver: local
